### ISSUE TITLE
SourcePlugin is not a function

### ISSUE THREAD

**Issue by bigblind** [carteb/carte-blanche#354]
I have my plugins set up as described in the README of this project, but I'm getting the following error:

````
/Users/frederikcreemers/dev/motocargo/frontend/webpack.config.js:34
            new SourcePlugin()
            ^

TypeError: SourcePlugin is not a function
    at Object.<anonymous> (/Users/frederikcreemers/dev/motocargo/frontend/webpack.config.js:34:13)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at module.exports (/Users/frederikcreemers/dev/motocargo/frontend/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/frederikcreemers/dev/motocargo/frontend/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:399:26)
```

I also got an unmet peerdependency when installing the sourceplugin:

    carte-blanche-source-plugin@0.1.0 requires a peer of carte-blanche@^0.1.0 but none was installed.

I'm using carte-blanche@0.2.3, so I suspect the source plugin has not been updated to the latest carte blanche v&ersion. Is this the problem, or am I doing something wrong?

**Comment by mxstbr** [comment]
Yeah that is a bug, we need to cut a new release! Meanwhile, can you see if `new SourcePlugin.default()` works?
