### ISSUE TITLE
"SourcePlugin is not a constructor"

### ISSUE THREAD

**Issue by kevinSuttle** [carteb/carte-blanche#368]
```js
plugins: [
   new SourcePlugin(),
   new ReactPlugin()
]
```

```js
TypeError: SourcePlugin is not a constructor
    at Object.<anonymous> (/Users/kevinSuttle/Code/platform-ui-primitives/webpack.config.js:43:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/kevinSuttle/Code/platform-ui-primitives/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/Users/kevinSuttle/Code/platform-ui-primitives/node_modules/webpack/bin/webpack.js:120:40)
```

```json
"webpack": "^2.1.0-beta.15",
"webpack-dev-server": "^2.1.0-beta.0",
"webpack-validator": "^2.2.1"
```

**Comment by mxstbr** [comment]
Damn, can you try `new SourcePlugin.default()`?

**Comment by hosmelq** [comment]
I sent a pull request for this. #316

**Comment by nikgraf** [comment]
@mxstbr we should cut a new release 😄

**Comment by mxstbr** [comment]
Yeah, we should. Closing this for now since it'll be resolved with the next release!
